# Generated by Django 2.1.4 on 2018-12-27 07:16

from django.db import migrations, models
import django_prices.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0083_auto_20181226_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='GST',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=django_prices.models.MoneyField(currency='INR', decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='cost_price',
            field=django_prices.models.MoneyField(blank=True, currency='INR', decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='price_override',
            field=django_prices.models.MoneyField(blank=True, currency='INR', decimal_places=2, max_digits=12, null=True),
        ),
    ]
