# Generated by Django 2.1.4 on 2018-12-24 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0068_order_shipping_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='shipping_company',
        ),
    ]
