# Generated by Django 2.1.4 on 2018-12-26 06:28

from django.db import migrations
import django_prices.models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0026_auto_20181226_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='balance',
            field=django_prices.models.MoneyField(currency='USD', decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
