# Generated by Django 2.1.4 on 2018-12-27 07:16

from django.db import migrations
import django_prices.models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0027_auto_20181226_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='balance',
            field=django_prices.models.MoneyField(currency='INR', decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
